server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    database: 0
    host: 8.129.177.173
    port: 6379
    password: 149526

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl